//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HallManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiningRegistration
    {
        public int id { get; set; }
        public string name { get; set; }
        public string desig { get; set; }
        public string home { get; set; }
        public string contact { get; set; }
        public string hall { get; set; }
        public string email { get; set; }
        public string pwd { get; set; }
        public string image { get; set; }
    }
}
