//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HallManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HallAdmission
    {
        public int id { get; set; }
        public string name { get; set; }
        public string stuid { get; set; }
        public string regg { get; set; }
        public string session { get; set; }
        public string faculty { get; set; }
        public string semester { get; set; }
        public string hall { get; set; }
        public string room { get; set; }
        public string amount { get; set; }
        public string status { get; set; }
    }
}
