//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HallManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sb2 : DbContext
    {
        public sb2()
            : base("name=sb2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DiningMenu> DiningMenus { get; set; }
        public virtual DbSet<DiningRegistration> DiningRegistrations { get; set; }
        public virtual DbSet<HallAdmission> HallAdmissions { get; set; }
        public virtual DbSet<ProvostPost> ProvostPosts { get; set; }
        public virtual DbSet<ProvostSpeech> ProvostSpeeches { get; set; }
        public virtual DbSet<ProvostsRegistration> ProvostsRegistrations { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<StudentInsecureMessage> StudentInsecureMessages { get; set; }
        public virtual DbSet<StudentPost> StudentPosts { get; set; }
        public virtual DbSet<StudentProvostSecretMsg> StudentProvostSecretMsgs { get; set; }
    }
}
