//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HallManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvostPost
    {
        public int id { get; set; }
        public string provostmessage { get; set; }
        public string title { get; set; }
        public string dateTime { get; set; }
        public string name { get; set; }
        public string desig { get; set; }
    }
}
