//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HallManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int id { get; set; }
        public string name { get; set; }
        public string faculty { get; set; }
        public string stuid { get; set; }
        public string reg { get; set; }
        public string session { get; set; }
        public string district { get; set; }
        public string contact { get; set; }
        public string blood { get; set; }
        public string hall { get; set; }
        public string email { get; set; }
        public string pwd { get; set; }
        public string image { get; set; }
        public string desig { get; set; }
    }
}
