//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HallManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPost
    {
        public int id { get; set; }
        public string studentpost1 { get; set; }
        public string name { get; set; }
        public string time { get; set; }
        public string date { get; set; }
    }
}
